import sqlite3 from 'sqlite3';
import { open } from 'sqlite';
import path from 'path';

export async function GET() {
  try {
    // Connect to the SQLite database generated by the Python ETL pipeline
    // The DB is located one directory above the Next.js frontend root
    const dbPath = path.join(process.cwd(), '../financial_news.db');
    
    const db = await open({
      filename: dbPath,
      driver: sqlite3.Database
    });

    // Query the articles, ordering by published date
    const articles = await db.all('SELECT * FROM articles ORDER BY publishedAt DESC');
    
    await db.close();

    return Response.json({ success: true, articles });
  } catch (error) {
    console.error('Database Error:', error);
    return Response.json({ success: false, error: 'Failed to fetch data' }, { status: 500 });
  }
}
